swagger: '2.0'
info:
  description: REST API of the Linux server from riotsensors
  version: "1.0"
  title: riotsensors REST API
  contact:
    email: patrick.grosse@uni-muenster.de
  license:
    name: Proprietary
schemes:
- http
definitions:
  LambdaId: &lambdaId
    description: ID of a registered lambda
    type: integer
    minimum: 0
    maximum: 255
  LambdaType: &lambdaType
    description: Type of a registered lambda
    type: integer
    minimum: 1
    maximum: 3
  LambdaName: &lambdaName
    description: Name of a registered lambda
    type: string
    minLength: 1
    maxLength: 12
paths:
  /call/id/{type}/{id}:
    get:
      operationId: callLambdaById
      summary: Call a lambda by it's ID
      produces:
      - application/json
      parameters:
      - in: path
        name: type
        required: true
        <<: *lambdaType
      - in: path
        name: id
        required: true
        <<: *lambdaId
      responses:
        200:
          description: "Success (success: `true`)"
          schema:
            $ref: '#/definitions/CallSuccess'
        400:
          description: Invalid type given
          schema:
            description: A string explaining a wrong type was given
            type: string
        500:
          description: "Error occurred while calling lambda (success: `false`)"
          schema:
            $ref: '#/definitions/CallFailure'
  /call/name/{type}/{name}:
    get:
      operationId: callLambdaByName
      summary:  Call a lambda by it's name
      produces:
      - application/json
      parameters:
      - in: path
        name: type
        required: true
        <<: *lambdaType
      - in: path
        name: name
        required: true
        <<: *lambdaName
      responses:
        200:
          description: "Success (success: `true`)"
          schema:
            $ref: '#/definitions/CallSuccess'
        400:
          description: Invalid type given
          schema:
            description: A string explaining a wrong type was given
            type: string
        500:
          description: "Error occurred while calling lambda (success: `false`)"
          schema:
            $ref: '#/definitions/CallFailure'
  /list:
    get:
      operationId: listLambdas
      summary: List all registered lambdas and their properties
      produces:
      - application/json
      parameters:
      - in: query
        name: type
        description: List only the lambdas of a specific type, type of the lambdas (see LambdaType)
        required: false
        <<: *lambdaType
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lambdas:
                description: All lambdas matched the query parameters
                type: array
                items:
                  $ref: '#/definitions/LambdaData'
              count:
                description: Amount of lambdas matched the query parameters
                type: integer
        400:
          description: Invalid type given
          schema:
            description: A string explaining a wrong type was given
            type: string
  /showcache:
    get:
      operationId: showLambdaCache
      summary: List all registered lambdas, their properties and the cached values, if available
      produces:
      - application/json
      parameters:
      - in: query
        name: type
        description: List only the lambdas of a specific type, type of the lambdas (see LambdaType)
        required: false
        <<: *lambdaType
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lambdas:
                description: All lambdas matched the query parameters
                type: object
                properties:
                  lambda_id:
                    description: Each lambda found is mapped by it's ID
                    type: object
                    properties:
                      lambda:
                        $ref: '#/definitions/LambdaData'
                      cache-content:
                        description: Information about the cache state of the lambda
                        type: object
                        required:
                          - cache-available
                        properties:
                          cache-available:
                            description: If a value is cached
                            type: boolean
                          cached-result:
                            $ref: '#/definitions/LambdaReturn'
              count:
                description: Amount of lambdas matched the query parameters
                type: integer
        400:
          description: Invalid type given
          schema:
            description: A string explaining a wrong type was given
            type: string
  /kill:
    get:
      operationId: shutdownServer
      summary: Shutdown the server and close the allocated resources properly
      produces:
      - text/plain
      responses:
        200:
          description: Success
          schema:
            description: A string explaining the server is going to be shutdown
            type: string
definitions:
  CallSuccess:
    type: object
    properties:
      success:
        description: Set to true on success
        type: boolean
      lambda:
        $ref: '#/definitions/LambdaData'
      cache:
        type: object
        description: State of the cache for this call
        properties:
          retrieved:
            description: If the value was retrieved from cache instead of directly from the device
            type: boolean
          timeout:
            description: If the value was retrieved from cache because an error occurred
            type: boolean
      result:
        $ref: '#/definitions/LambdaReturn'
  CallFailure:
    type: object
    properties:
      success:
        description: Set to false on errors
        type: boolean
      lambda:
        $ref: '#/definitions/LambdaData'
      error:
        type: object
        properties:
          code:
            description: Error code
            type: integer
          string:
            description: Human readable error description
            type: string
  LambdaData:
    description: A registered lambda and all it's properties
    type: object
    properties:
      id:
        $ref: '#/definitions/LambdaId'
      name:
        $ref: '#/definitions/LambdaName'
      type:
        description: Information about the type of the lambda
        type: object
        properties:
          code:
            $ref: '#/definitions/LambdaType'
          string:
            description: Human readable string of lambda type
            type: string
      cache:
        description: Information about the cache of the lambda
        type: object
        properties:
          policy:
            description: Cache policy of the lambda
            type: integer
          string:
            description: Human readable string of cache policy
            type: string
  LambdaId:
    <<: *lambdaId
  LambdaType:
    <<: *lambdaType
  LambdaName:
    <<: *lambdaName
  LambdaReturn:
    description: Return value of a lambda, can be either an integer, a double or a string (determined by the lambda type) LambdaIntReturn, LambdaDoubleReturn, LambdaStringReturn
    type: object
    allOf:
      - $ref: '#/definitions/LambdaIntReturn'
      - $ref: '#/definitions/LambdaDoubleReturn'
      - $ref: '#/definitions/LambdaStringReturn'
  LambdaIntReturn:
    type: integer
  LambdaDoubleReturn:
    type: number
  LambdaStringReturn:
    type: string