image: patgrosse/bachelor
stages:
  - prepare
  - cmake
  - buildProtocol
  - build
  - test
  - buildServer
  - docs
#cache:
#  key: "$CI_BUILD_REF_NAME"
#  paths:
#    - lib/gcc-arm-none-eabi-6_2-2016q4-20161216-linux.tar.bz2
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
getlibs:
  variables:
    GIT_STRATEGY: clone
  stage: prepare
  script:
    - "./prebuild.sh"
  artifacts:
    paths:
    - lib/
cmake:
  variables:
    GIT_STRATEGY: none
  stage: cmake
  dependencies:
    - getlibs
  script:
    - "mkdir -p build"
    - "cd build"
    - "cmake .."
  artifacts:
    paths:
    - build/
build:protocol:
  variables:
    GIT_STRATEGY: none
  stage: buildProtocol
  dependencies:
    - cmake
    - getlibs
  script:
    - "cd build/protocol"
    - "make"
  artifacts:
    paths:
    - build/
build:RIOTmodule:
  variables:
    GIT_STRATEGY: none
  stage: build
  dependencies:
    - getlibs
    - build:protocol
  script:
    - "cd build/riotmodule"
    - "make"
  artifacts:
    paths:
    - build/
build:linuxconnector:
  variables:
    GIT_STRATEGY: none
  stage: build
  dependencies:
    - getlibs
    - build:protocol
  script:
    - "cd build/linuxconnector"
    - "make"
  artifacts:
    paths:
    - build/
build:restserver:
  variables:
    GIT_STRATEGY: none
  stage: buildServer
  dependencies:
    - getlibs
    - build:linuxconnector
  script:
    - "cd build/restserver"
    - "make"
  artifacts:
    paths:
    - build/
test:protocol:
  variables:
    GIT_STRATEGY: none
  stage: test
  dependencies:
    - build:protocol
  script:
    - "cd build/protocol/tests"
    - "./protocol_tests"
test:RIOTmodule:
  variables:
    GIT_STRATEGY: none
  stage: test
  dependencies:
    - build:RIOTmodule
  script:
    - "cd build/riotmodule/tests"
    - "./riot_tests"
test:linuxconnector:
  variables:
    GIT_STRATEGY: none
  stage: test
  dependencies:
    - build:linuxconnector
  script:
    - "cd build/linuxconnector/tests"
    - "./linux_tests"
doxygenDocs:
  variables:
    GIT_STRATEGY: none
  stage: docs
  dependencies: []
  before_script: []
  image: iimuz/doxygen
  when: always
  script:
    - "mkdir -p build/doxygen"
    - "doxygen Doxyfile"
  artifacts:
    paths:
      - "build/doxygen"