image: rikorose/gcc-cmake
stages:
  - build
  - test
  - docs
#cache:
#  key: "$CI_BUILD_REF_NAME"
#  paths:
#    - lib/gcc-arm-none-eabi-6_2-2016q4-20161216-linux.tar.bz2
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - "./prebuild.sh"
build:RIOTmodule:
  stage: build
  script:
    - "mkdir -p build"
    - "cd build"
    - "cmake .."
    - "make"
  artifacts:
    paths:
    - build/
test:RIOTmodule:
  stage: test
  before_script: []
  dependencies:
    - build:RIOTmodule
  script:
    - "cd build/riotmodule/tests"
    - "./runTests"
doxygenDocs:
  stage: docs
  before_script: []
  image: iimuz/doxygen
  when: always
  script:
    - "mkdir -p build/doxygen"
    - "doxygen Doxyfile"
  artifacts:
    paths:
      - "build/doxygen"